---
name: CI

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
      - gha-*
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+.x

jobs:
  tests:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      # - name: Check code style
      #   run: make quality
      # - name: Install test package
      #   run: python setup.py develop
      # - name: Run pytest
      #   run: make test_norecord
      # - name: Upload coverage data to coveralls.io
      #   run: coveralls --service=github
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
      #     COVERALLS_PARALLEL: true

  # coveralls:
  #   name: Finalize job on coveralls.io
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   container: python:3-slim
  #   steps:
  #     - name: Notify coveralls.io
  #       run: |
  #         pip install --upgrade coveralls
  #         coveralls --finish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
